FROM node:lts-alpine

RUN npm install -g pnpm

WORKDIR /workspace

COPY package.json pnpm-lock.yaml ./

RUN pnpm i --frozen-lockfile --ignore-scripts --store-dir /share/.pnpm-store && rm -rf ./node_modules
